# Weather prediction
- platform: yr

# RaspberryPi temperature
- platform: command_line
  name: Pi Temp
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(2) }}'
