resources:
  - url: /local/custom_ui/weather-card.js?v=0.24
    type: module
  - url: /local/custom_ui/pc-card.js?v=0.2
    type: module
  - url: /local/custom_ui/circle-sensor-card.js
    type: module
  - url: /local/custom_ui/thermostat-card.js?v=1.3
    type: module
  - url: /local/custom_ui/calendar-card.js
    type: module
  - url: https://unpkg.com/moment@2.22.2/moment.js
    type: js
  - url: /local/custom_ui/slider-entity-row.js?v=0.3
    type: js
  - url: /local/custom_ui/button-card.js?v=0.12
    type: module
  - url: /local/custom_ui/mini-media-player-bundle.js?v=0.0.3
    type: module
  - url: /local/custom_ui/mini-graph-card-bundle.js?v=0.0.1
    type: module
  - url: /local/custom_ui/card-tools.js?v=0.1
    type: js
  - url: /local/custom_ui/gap-card.js?v=0.1
    type: js
  - url: /local/custom_ui/layout-card.js?v=0.1
    type: js
  - url: /local/custom_ui/card-modder.js?v=0.1
    type: js
  - url: /local/custom_ui/auto-entities.js?v=0.1
    type: js
  - url: /local/custom_ui/config-template-card.js?v=0.1
    type: module
  - url: /local/custom_ui/secondaryinfo-entity-row.js
    type: module

title: Home
views:
  - icon: mdi:home-assistant
    id: home
    title: Home
    cards:
      # Floor plan ----
      - type: picture-elements
        image: /local/img/floor-plan.png
        #title: Plan
        elements:
          - type: state-icon
            entity: binary_sensor.door
            style:
              top: 8%
              left: 37%
          - type: state-icon
            entity: binary_sensor.hallway_motion
            style:
              top: 40%
              left: 38%
          - type: state-icon
            entity: binary_sensor.green_motion
            style:
              top: 46%
              left: 68%
      # Last values -----
      - type: entities
        # title: Entrance
        show_header_toggle: false
        entities:
          #- binary_sensor.door
          #- binary_sensor.hallway_motion
          - sensor.door_last_close
          - sensor.hallway_last_motion
          - sensor.green_last_motion

      # Persons ----
      - type: entities
        # title: Persons
        show_header_toggle: false
        entities:
          - entity: person.dominykas
            secondary_info: last-changed
          - entity: person.egle
            secondary_info: last-changed
          - entity: person.mindaugas
            secondary_info: last-changed

            
  - icon: mdi:lan
    id: devices
    title: Devices
    cards:
      - type: gauge
        entity: sensor.pi_temp
        name: CPU temp
        severity:
          green: 0
          yellow: 45
          red: 85
          
      - type: sensor
        name: 'CPU Temp'
        entity: sensor.pi_temp
        graph: line
        detail: 2
        hours_to_show: 24
  
      - type: entities
        title: Network
        show_header_toggle: false
        entities:
          - device_tracker.desktop_djmci5b_dlink
          - device_tracker.dlinkrouter_dlink
          - device_tracker.sonoff_0662_dlink
          - device_tracker.00_12_fb_a9_cd_f4
          - device_tracker.chromecast_dlink
          - device_tracker.google_home_mini_dlink
          - device_tracker.samsung_dlink
