resources:
  - url: /local/custom_ui/weather-card.js?v=0.24
    type: module
  - url: /local/custom_ui/pc-card.js?v=0.2
    type: module
  - url: /local/custom_ui/circle-sensor-card.js
    type: module
#  - url: /local/custom_ui/thermostat-card.js?v=1.3
#    type: module
#  - url: /local/custom_ui/calendar-card.js
#    type: module
  - url: https://unpkg.com/moment@2.22.2/moment.js
    type: js
  - url: /local/custom_ui/slider-entity-row.js?v=0.3
    type: js
  - url: /local/custom_ui/button-card.js?v=0.12
    type: module
  - url: /local/custom_ui/mini-media-player-bundle.js?v=0.0.3
    type: module
  - url: /local/custom_ui/mini-graph-card-bundle.js?v=0.0.1
    type: module
  - url: /local/custom_ui/card-tools.js?v=0.1
    type: js
  - url: /local/custom_ui/gap-card.js?v=0.1
    type: js
  - url: /local/custom_ui/layout-card.js?v=0.1
    type: js
  - url: /local/custom_ui/card-modder.js?v=0.1
    type: js
  - url: /local/custom_ui/auto-entities.js?v=0.1
    type: js
  - url: /local/custom_ui/config-template-card.js?v=0.1
    type: module
  - url: /local/custom_ui/secondaryinfo-entity-row.js
    type: module

title: Home
views:
  - icon: mdi:home-assistant
    id: home
    title: Home
    cards:



#      # Floor plan ----
#      - type: picture-elements
#        image: /local/img/floor-plan.png
#        #title: Plan
#        elements:
#          # Door
#          - type: state-icon
#            entity: binary_sensor.door
#            style:
#              top: 8%
#              left: 37%
#          # Hallway
#          - type: state-icon
#            entity: binary_sensor.hallway_motion
#            style:
#              top: 40%
#              left: 38%
#          # Green
#          - type: state-icon
#            entity: binary_sensor.green_motion
#            style:
#              top: 46%
#              left: 68%
#          # Safe 1
#          - type: state-icon
#            entity: binary_sensor.safe_1
#            style:
#              top: 90%
#              left: 65%
#              "--paper-item-icon-color": silver
#              "--paper-item-icon-active-color": red
#          # Safe 1
#          - type: state-icon
#            entity: binary_sensor.safe_2
#            style:
#              top: 90%
#              left: 75%
#              "--paper-item-icon-color": silver
#              "--paper-item-icon-active-color": red


          
      # Persons ----
      - type: entities
        # title: Persons
        show_header_toggle: false
        entities:
          - entity: person.dominykas
            secondary_info: last-changed
          - entity: person.egle
            secondary_info: last-changed
          - entity: person.mindaugas
            secondary_info: last-changed
          - entity: sensor.door_last_close
            secondary_info: last-changed


      - type: horizontal-stack
        cards:
        - type: sensor
          name: "Living Room"
          entity: sensor.yellow_temperature
          #graph: line
        - type: sensor
          name: "Humidor"
          entity: sensor.humidor_humidity
          #graph: line


      - type: entities
        show_header_toggle: false
        entities:
          - entity: sensor.yellow_temperature
            name: Living Room temperature
          - entity: sensor.yellow_humidity
            name: Living Room humidity
          - type: divider
          - entity: sensor.blue_temperature
            name: Bedroom temperature
          - entity: sensor.blue_humidity
            name: Bedroom humidity
          - type: divider
          - sensor.humidor_temperature
          - sensor.humidor_humidity






  - icon: mdi:cctv
    id: charts
    title: Securty
    cards:

      # Floor plan 3D ----
      - type: picture-elements
        image: /local/img/3D-1024.jpg
        elements:
          # Door
          - type: state-icon
            entity: binary_sensor.door
            style:
              top: 10%
              left: 46%
              "--paper-item-icon-active-color": red
          # Hallway
          - type: state-icon
            entity: binary_sensor.hallway_motion
            style:
              top: 43%
              left: 43%
              "--paper-item-icon-active-color": red
          # Green
          - type: state-icon
            entity: binary_sensor.green_motion
            style:
              top: 40%
              left: 78%
              "--paper-item-icon-active-color": red
          # Blue
          - type: state-icon
            entity: binary_sensor.blue_motion
            style:
              top: 20%
              left: 78%
              "--paper-item-icon-active-color": red
          # Safe 1
          - type: state-icon
            entity: binary_sensor.safe_1
            style:
              top: 90%
              left: 73%
              "--paper-item-icon-color": silver
              "--paper-item-icon-active-color": red
          # Safe 1
          - type: state-icon
            entity: binary_sensor.safe_2
            style:
              top: 90%
              left: 82%
              "--paper-item-icon-color": silver
              "--paper-item-icon-active-color": red
          # temp
          #- type: state-icon
          #  entity: sensor.yellow_temperature
          #  style:
          #    top: 84.5%
          #    left: 42%
          #    color: white
          #    --iron-icon-height: 10px
          #    --iron-icon-width: 10px

          # temp yellow
          - type: state-label
            entity: sensor.yellow_temperature
            style:
              top: 85%
              left: 46%
              color: "#44739e"
              font-size: "10px"
          - type: state-label
            entity: sensor.yellow_humidity
            style:
              top: 88%
              left: 46%
              color: "#44739e"
              font-size: "10px"
          # temp blue
          - type: state-label
            entity: sensor.blue_temperature
            style:
              top: 18%
              left: 84%
              color: "#44739e"
              font-size: "10px"
          - type: state-label
            entity: sensor.blue_humidity
            style:
              top: 21%
              left: 84%
              color: "#44739e"
              font-size: "10px"


      # Last values -----
      - type: entities
        # title: Entrance
        show_header_toggle: false
        entities:
          #- binary_sensor.door
          #- binary_sensor.hallway_motion
          - entity: sensor.door_last_close
            secondary_info: last-changed
          - entity: sensor.hallway_last_motion
            secondary_info: last-changed
          - entity: sensor.blue_last_motion
            secondary_info: last-changed
          - entity: sensor.green_last_motion
            secondary_info: last-changed
          - entity: sensor.last_motion_location

      # Safes
      - type: entities
        entities:
          - entity: binary_sensor.safe_1
            secondary_info: last-changed
          - entity: binary_sensor.safe_2
            secondary_info: last-changed



  - icon: mdi:chart-line
    id: charts
    title: History
    cards:
      - type: history-graph
        title: Temperature
        entities:
          - entity: sensor.yellow_temperature
            name: Living
          - entity: sensor.blue_temperature
            name: Bedroom
          - entity: sensor.humidor_temperature
            name: Humidor
      - type: history-graph
        title: Humidity
        entities:
          - entity: sensor.yellow_humidity
            name: Living
          - entity: sensor.blue_humidity
            name: Bedroom
          - entity: sensor.humidor_humidity
            name: Humidor

            
  - icon: mdi:lan
    id: devices
    title: Devices
    cards:
      - type: sensor
        name: 'CPU Temp'
        entity: sensor.pi_temp
        graph: line
        detail: 2
        hours_to_show: 24

      - type: entities
        title: System
        show_header_toggle: false
        entities:
          - sensor.processor_use
          - sensor.memory_free
          - sensor.disk_free_home
          - sensor.last_boot

      - type: entities
        title: Devices
        show_header_toggle: false
        entities:
          - device_tracker.desktop_djmci5b_dlink
          - device_tracker.dlinkrouter_dlink
          - device_tracker.sonoff_0662_dlink
          - device_tracker.00_12_fb_a9_cd_f4
          - device_tracker.chromecast_dlink
          - device_tracker.google_home_mini_dlink
          - device_tracker.samsung_dlink
          - device_tracker.shellyht_58f5e2_dlink
          - device_tracker.shellyht_58fb74_dlink
          - device_tracker.shellyht_58f788_dlink

      - type: entities
        title: Network
        show_header_toggle: false
        entities:
          - sensor.dir_825acg1_kbyte_sec_received
          - sensor.dir_825acg1_kbyte_sec_sent

      - type: entities
        title: Bateries
        show_header_toggle: false
        entities:
          - entity: sensor.yellow_battery
            name: Shelly Living Room
          - entity: sensor.blue_battery
            name: Shelly Bedroom Room
          - entity: sensor.humidor_battery
            name: Shelly Humidor
